### ISSUE TITLE
Can't find license files of dict-v0.0.1.zip

### ISSUE THREAD

**Issue by neologd** [debate-info-lab/sep-speech-tools#1]
Thank you for using mecab-ipadic-NEologd.

I confirmed the contents of dict-v.0.0.1.zip.
In conclusion, the sys.dic you are distributing uses the seed file of mecab-ipadic-NEologd.
The license of mecab-ipadic-NEologd is 'Apache License, Version 2.0'.
I would like you to comply with this license.

https://github.com/neologd/mecab-ipadic-neologd/blob/master/COPYING

Also, the license file of mecab-ipadic is not included.
I'm  paying attention not to distribute mecab-ipadic resources.
However, sys.dic created with a script file of mecab-ipadic-NEologd contains the resources of mecab-ipadic.
Since the license of mecab-ipadic is a proprietary format, we also advise you to comply.

https://github.com/taku910/mecab/blob/master/mecab-ipadic/COPYING

**Comment by mugwort-rc** [comment]
Sorry, my mistake.

I've added LICENSE.md to dict-v0.0.1a.zip.

Thank you for pointing out.
